name: play_match
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dyte_core:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  fluttertoast:
  font_awesome_flutter:
  get:
  google_fonts:
  intl:
  lottie:
  permission_handler:
  pinput:
  provider:
  shared_preferences:
  smooth_page_indicator:
  stroke_text:
  blur:

flutter:
  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: sahuIt
      fonts:
        - asset: font/SahurBosku-ScriptItalic.ttf
    - family: Univers
      fonts:
        - asset: font/Univers-Next-Pro-Heavy-Italic.ttf
    - family: pajaro
      fonts:
        - asset: font/-OCPajaro-Medium.ttf

