List<String> sexualOriantetionList = [
  'Lesbian',
  'Gay',
  'Bisexual',
  'Pansexual',
  'Asexual',
  'Demisexual',
  'Sapiosexual',
  'Heteroflexible',
  'Non-monosexual',
  'Polysexual',
  'Questioning',
  'Queer',
  'Same-sex attraction',
  'Undecided',
  'Prefer not to say',
];

const List<String> genZHobbies = [
  'BeatDroppin',
  'MemeMaster',
  'ThriftAndFlip',
  'FoodieFam',
  'PlantParent',
  'WanderlustWarriors',
  'DIYDreams',
  'GamerGang',
  'SquadGoals',
  'FitnessFanatics',
  'BrainiacsAndBookworms',
  'ArtsyFartsy',
  'AnimeAddicts',
  'LanguageLearners',
  'FilmBuffsAndBingers',
  'SocialJusticeWarriors',
  'TechTakeover',
  'MysticVibes',
  'MakeupMavens',
  'PetParents',
];
